feat(types): implement Message.CommandArguments() method
bots-house/go-tg pull request #6
Opened 2020-10-08 16:26 UTC by chicksick

2020-10-08 16:31 UTC, mr-linch requested changes

2020-10-08 16:31 UTC, mr-linch commented on types.go
> +func (msg *Message) IsCommand() bool {
may be `strings.HasPrefix(text, '/')`

2020-10-08 16:31 UTC, mr-linch commented on types.go
> +func (msg *Message) CommandArguments() string {
may be `strings.SplitN(msg.Text, ' ', 1)`?

2020-10-08 16:31 UTC, mr-linch commented on types.go
> +func (msg *Message) CommandArguments() string {
too long, just CommandArgs()

2020-10-08 16:37 UTC, chicksick commented on types.go
> +func (msg *Message) IsCommand() bool {
Конечно это маловероятно но, что делать если текст сообщение такой:
<code>/test ...</code> - это уже не команда

2020-10-08 16:41 UTC, mr-linch requested changes

2020-10-08 16:41 UTC, mr-linch commented on types.go
> +func (msg *Message) IsCommand() bool {
это не команда 
команда все то что начинается с /

2020-10-09 11:37 UTC, mr-linch approved these changes

2020-10-09 11:38 UTC, merged